Fix #712
When an application both

* returns an iterable
* calls start_response *after* a part of the response has
  been consumed

run_wsgi_app breaks in unbuffered mode:

      File "/Users/kakashi/Programs/project/.env/lib/python2.7/site-packages/werkzeug/test.py", line 873, in run_wsgi_app
        buffer.append(next(app_iter))
    TypeError: _WSGIApplicationIterable object is not an iterator

See https://discuss.newrelic.com/t/werkzeug-cant-work-properly-when-using-agent-2-40-0-34/13318/4
and https://github.com/mitsuhiko/werkzeug/issues/712