test: accept fd for post() data parameter (#1011)
It's possible to pass an open file descriptor to the post() method
of requests. This patch ensures the test client also accepts the
parameter instead of this error message:

    E   AttributeError: 'file' object has no attribute 'iteritems'

See: http://docs.python-requests.org/en/master/api/#requests.post